import { CLI_VERSION } from './version.js';
import { presetText } from './presets.js';

export function englishHelpText() {
  return `YTConv CLI v${CLI_VERSION}\n\n`
    + 'Usage:\n'
    + '  ytconv download URL [OPTIONS]\n'
    + '  ytconv playlist URL [OPTIONS]\n'
    + '  ytconv batch links.txt [OPTIONS]\n'
    + '  ytconv info URL --json\n'
    + '  ytconv formats URL [--json]\n'
    + '  ytconv [URL] [OPTIONS]  (legacy-compatible)\n\n'
    + 'Playlist, batch, and reliability:\n'
    + '  --playlist / --playlist-items ITEMS / --max-downloads N\n'
    + '  --archive FILE / --skip-playlist-after-errors N\n'
    + '  --retries N|infinite / --fragment-retries N|infinite\n'
    + '  --file-access-retries N / --retry-sleep EXPR\n'
    + '  --resume / --no-resume / --cleanup-part\n\n'
    + 'Formats and quality:\n'
    + '  --format FORMAT        Generic audio/video format\n'
    + '  --quality VALUE        Audio bitrate or video resolution\n'
    + '  --audio-format FORMAT  mp3, m4a, aac, opus, vorbis, flac, alac, wav\n'
    + '  --audio-quality RATE   best, 320, 256, 192, 128, 96\n'
    + '  --video-format FORMAT  auto, mp4, mkv, webm\n'
    + '  --resolution SIZE      best through 144p\n\n'
    + 'Metadata, cover art, and subtitles:\n'
    + '  --metadata --thumbnail --metadata-files\n'
    + '  --artist/--title/--album/--track/--year/--genre VALUE\n'
    + '  --subtitles / --subtitle-only / --subtitle-langs LANGS\n'
    + '  --start/--end TIME     Aliases: --from/--to\n'
    + '  --sponsorblock MODE / --normalize-audio\n\n'
    + 'Cookies and authentication:\n'
    + '  --cookies FILE\n'
    + '  --cookies-from-browser chrome|chromium|edge|firefox|brave[:PROFILE]\n\n'
    + 'Files and performance:\n'
    + '  --concurrent-fragments N / --rate-limit RATE / --proxy URL\n'
    + '  --output-template TEMPLATE / --restrict-filenames / --overwrite\n'
    + '  -o, --output PATH / --log-file FILE\n\n'
    + 'Inspection without downloading:\n'
    + '  --dry-run / --json / --list-formats / --formats-json / --list-subs\n\n'
    + 'System:\n'
    + '  --diagnose / --check-update / --update / --no-update-check\n'
    + '  -h, --help / -v, --version / -y, --yes\n\n'
    + 'Quality note: MP3 320 kbps is an encoder target and cannot add detail missing from the source.\n\n'
    + 'Presets:\n'
    + `${presetText()}\n`;
}
